### ISSUE TITLE
Files not found during wget

### ISSUE THREAD

**Issue by RobPellowski** [shenki/openbmc-qemu-tutorial#1]
Running `build.sh` exits with the following:
```
--2022-04-08 12:13:50--  https://jenkins.openbmc.org/job/latest-master/label=docker-builder,target=romulus/lastSuccessfulBuild/artifact/openbmc/build/tmp/deploy/images/romulus/obmc-phosphor-initramfs-romulus.cpio.xz
Resolving jenkins.openbmc.org (jenkins.openbmc.org)... 169.44.58.24
Connecting to jenkins.openbmc.org (jenkins.openbmc.org)|169.44.58.24|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-08 12:13:50 ERROR 404: Not Found.

--2022-04-08 12:13:50--  https://jenkins.openbmc.org/job/latest-master/label=docker-builder,target=romulus/lastSuccessfulBuild/artifact/openbmc/build/tmp/deploy/images/romulus/flash-romulus
Resolving jenkins.openbmc.org (jenkins.openbmc.org)... 169.44.58.24
Connecting to jenkins.openbmc.org (jenkins.openbmc.org)|169.44.58.24|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-08 12:13:51 ERROR 404: Not Found.
```

**Comment by shenki** [comment]
Hi Rob, it appears the CI has changed the location of the files. If you take a look on jenkins.openbmc.org for the newer URLs for the Romulus flash and initramfs files, I'd happily merge a pull request with the updated paths.

**Comment by RobPellowski** [comment]
Hi Joel,

Unfortunately it's somewhat complicated. The flash is shown as
obmc-phosphor-image-romulus-20220411025146.static.mtd.tar
<https://jenkins.openbmc.org/job/latest-master/label=docker-builder,target=romulus/lastSuccessfulBuild/artifact/openbmc/build/tmp/deploy/images/romulus/obmc-phosphor-image-romulus-20220411025146.static.mtd.tar>
but also is copied as
obmc-phosphor-image-romulus.static.mtd
<https://jenkins.openbmc.org/job/latest-master/label=docker-builder,target=romulus/lastSuccessfulBuild/artifact/openbmc/build/tmp/deploy/images/romulus/obmc-phosphor-image-romulus.static.mtd>

The initramfs looks to be
obmc-phosphor-initramfs-romulus-20220411025146.rootfs.cpio.xz
<https://jenkins.openbmc.org/job/latest-master/label=docker-builder,target=romulus/lastSuccessfulBuild/artifact/openbmc/build/tmp/deploy/images/romulus/obmc-phosphor-initramfs-romulus-20220411025146.rootfs.cpio.xz>
but has no corresponding generic name. Every build has a new name.

Awesome tutorial BTW, I've learned a lot.

Rob

**Comment by shenki** [comment]
Thanks for the feedback, I appreciate it.

It's annoying that jenkins stopped exposing the symlinks. That broke scripts I had too. We should fix the build to copy the artifacts to a known filename.

For now, we can use historical releases:

 https://github.com/openbmc/openbmc/releases/download/2.9.0/obmc-phosphor-image-romulus.static.mtd

But that doesn't contain an initramfs. Bummer.

Instead I've downloaded the files and placed them here:

https://ozlabs.org/~joel/openbmc-qemu-tutorial/

**Comment by shenki** [comment]
I decided to put the files directly in the repository as there's not a big difference between that and having them on ozlabs.org.

The downside of this approach is it's an old version of the BMC, but for the tutorials purposes that doesn't really matter.

**Comment by RobPellowski** [comment]
See [this issue](https://github.com/openbmc/docs/issues/73) in openbmc regarding another file. Their solution was to copy to a generic name as part of the build process.
